# The materials you wish to have decayed. Each group name needs to be unique, and each material can be present in only one (1) group.
# !!! CAUTION !!!
# !!! Currently can trigger ANY material listed on https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html !!!
DecayingFoodGroups:
  Meats:
    RateOfDecay: 45 #in seconds
    DecayingFoods:
      - 'Beef'
      - 'Chicken'
      - 'Porkchop'
      - 'rabbit stew'
  Fish:
    RateOfDecay: 30 #in seconds
    DecayingFoods:
      - 'Cod'
      - 'Salmon'
  Plants:
    RateOfDecay: 60 #in seconds
    DecayingFoods:
      - 'Bread'
      - 'Mushroom stew'
      - 'wheat'

# These materials will stop decay while they're in the same inventory as items in DecayingFoods.
# !!! CAUTION !!!
# !!! Will only respond to any materials with the word 'ice' in them !!!
DecayStoppers:
  - 'Ice'
  - 'Packed Ice'
  - 'blue ice'

RateOfDecay: 120 #in seconds
DecayCheckInterval: 10 #in seconds

Worlds:
  - 'Testing'
  #- 'World'

# !!! CAUTION !!!
# !!! Below are advanced settings, and are only meant to be changed if you understand the repercussions !!!

# These events are directly tied to when decaying foods are checked if they have their time of decay, and add it if it isn't yet.
# The default values should offer a more, if not most, optimized net to catch all situations. If it still falls short,
# you can turn more checks on at the risk of reducing performance.
OnDropFromBlockBreak: true
OnContainerLootGenerated: true
OnDropFromEntityDeath: true
OnFishedUp: true
OnPickupByPlayer: false
OnPickupByHopper: false
OnNonPlayerMoveToOtherInventory: false
OnPlayerPickupFromOtherInventory: false
OnTradeForFood: true
OnCraftingFood: true

# !!! CAUTION !!!
# !!! Messing with the values under here might seriously break the plugin !!!
# !!! Under no circumstance, change these values !!!
Version: 0