# The materials you wish to have decayed. Each group name needs to be unique, and each material can be present in only one (1) group.
# !!! CAUTION !!!
# !!! Currently can trigger ANY material listed on https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html !!!
DecayingFoodGroups:
  Meats:
    RateOfDecay: 60 #in seconds
    DecayingFoods:
      - 'Beef'
      - 'Chicken'
      - 'Porkchop'
      - 'rabbit stew'
      - 'cooked_porkchop'
      - 'cooked salmon'
  Fish:
    RateOfDecay: 30 #in seconds
    DecayingFoods:
      - 'Cod'
      - 'Salmon'
  Plants:
    RateOfDecay: 120 #in seconds
    DecayingFoods:
      - 'Bread'
      - 'Mushroom stew'
      - 'wheat'

# These materials will stop decay while they're in the same inventory as items in DecayingFoods.
# !!! CAUTION !!!
# !!! Will only respond to any materials with the word 'ice' in them !!!
DecayStoppers:
  - 'Ice'
  - 'Packed Ice'
  - 'blue ice'

DecayCheckInterval: 10 #in seconds

# Simple decay check will perform all checks for decay and pausing each decay interval.
# This reduces the amount of CPU used throughout server uptime even if it's more in peaks,
# but at the same time is less accurate the more time is between intervals, and makes small
# differences in rate of decay between food groups have less of an effect.
# !!! CAUTION !!!
# !!! Changing this setting to false will use an incomplete check in development !!!
UseSimpleDecayCheck: true

Worlds:
  - 'testing'
  - 'testing_nether'
  #- 'Random comment'
  #- 'testing some more'

# !!! CAUTION !!!
# !!! Messing with the values under here might seriously break the plugin !!!
# !!! Under no circumstance, change these values !!!
Version: 0